#!/usr/bin/env bash
# Shared helpers. Sourced, never executed.

# Reject anything that could escape the target tree or reach a shell/sed
# program. Used for every caller-supplied path fragment, because these
# fragments reach `rm -rf` and text substitution.
#
# Allowed: relative, single-line, [A-Za-z0-9._/-], no "." or ".." segment,
# no leading slash, no empty segment.
validate_rel_path() {
  local val="$1" what="$2" seg

  [ -n "$val" ]                     || { echo "$what must not be empty" >&2; return 1; }
  case "$val" in
    /*)      echo "$what must be relative, got absolute path: $val" >&2; return 1 ;;
    *[!A-Za-z0-9._/-]*)
             echo "$what may only contain A-Za-z0-9._/- : $val" >&2; return 1 ;;
  esac
  # Segment-wise check catches ../x, x/.., x/../y, and empty segments (x//y).
  local IFS=/
  # shellcheck disable=SC2086
  for seg in $val; do
    case "$seg" in
      ""|"."|"..") echo "$what must not contain '.', '..', or empty segments: $val" >&2; return 1 ;;
    esac
  done
  # A trailing slash produces no empty segment under word splitting; catch it.
  case "$val" in */) echo "$what must not end with '/': $val" >&2; return 1 ;; esac
  return 0
}

# Literal substitution with no program-injection surface: pure bash parameter
# expansion, never `sed`/`eval`. Reads stdin, writes stdout.
#   substitute_literal "<skill>" "skills/ui-qa" < in > out
# Text embedded in every GENERATED stub. Its presence is what authorizes
# overwriting or pruning that file: a path we did not generate is never touched,
# because a user may legitimately keep their own skill, agent, or command at the
# same conventional location.
UI_QA_GEN_MARKER="GENERATED by scripts/sync-platform-dirs.sh"

# 0 if the file is absent (safe to create) or carries the generated marker.
# 1 if it exists and is not ours.
is_generated_or_absent() {
  local path="$1"
  [ -e "$path" ] || [ -L "$path" ] || return 0
  [ -f "$path" ] || return 1
  grep -qF -- "$UI_QA_GEN_MARKER" "$path" 2>/dev/null
}

# Platform directories whose contents this generator owns. A --dest inside one of
# them would make the canonical skill and its own pointer stub the same file.
UI_QA_PLATFORM_ROOTS=".claude .codex .agents .cursor .gemini"

is_platform_path() {
  local first="${1%%/*}"
  case " $UI_QA_PLATFORM_ROOTS " in *" $first "*) return 0 ;; esac
  return 1
}

# Marker written into every directory this installer owns. Its presence is what
# authorizes deletion on upgrade -- a path we did not create is never removed,
# however it got into the config.
UI_QA_MARKER=".ui-qa-managed"

# Directories a caller may never target, whatever the manifest says.
# .git heads the list because deleting it destroys the repository.
is_forbidden_dest() {
  local val="$1" first="${1%%/*}"
  case "$first" in
    .git|.github|.githooks|node_modules) return 0 ;;
  esac
  case "$val" in
    .git|.git/*) return 0 ;;
  esac
  return 1
}

# Refuse to write through a symlink. Every component of REL under ROOT must be a
# real directory (or absent); a symlinked component can redirect writes outside
# the repository entirely.
assert_no_symlink_path() {
  # Declared separately: `local a=$1 b=$a` leaves b unset under `set -u`,
  # because bash creates every name in one `local` before assigning any.
  local root="$1"
  local rel="$2"
  local cur="$root"
  local seg
  local IFS=/
  # shellcheck disable=SC2086
  for seg in $rel; do
    [ -n "$seg" ] || continue
    cur="$cur/$seg"
    if [ -L "$cur" ]; then
      echo "refusing to write through symlink: $cur" >&2
      return 1
    fi
  done
  return 0
}

# mkdir -p that fails instead of following a symlinked component.
safe_mkdir_p() {
  local root="$1" rel="$2"
  assert_no_symlink_path "$root" "$rel" || return 1
  mkdir -p "$root/$rel"
}

# Prepare a file path for writing: no symlinked parent, and if the target itself
# is a symlink, remove the link rather than writing through it.
safe_prepare_file() {
  local root="$1" rel="$2" dir
  dir="$(dirname "$rel")"
  [ "$dir" = "." ] && dir=""
  [ -z "$dir" ] || { safe_mkdir_p "$root" "$dir" || return 1; }
  assert_no_symlink_path "$root" "$rel" || return 1
  [ -L "$root/$rel" ] && rm -f "$root/$rel"
  return 0
}

substitute_literal() {
  local needle="$1" replacement="$2" line
  while IFS= read -r line; do
    printf '%s\n' "${line//"$needle"/"$replacement"}"
  done
  # A file with no trailing newline leaves its last line in $line unprinted.
  if [ -n "${line-}" ]; then
    printf '%s' "${line//"$needle"/"$replacement"}"
  fi
}
