#!/usr/bin/env python3
"""Derive host manifests, catalogs, and a Claude agent from one plugin package.

JSON outputs have adjacent ownership markers because host schemas do not all
allow generator metadata. --check is read-only. Never copies the skill.
"""
import argparse
import json
from pathlib import Path
import sys

MARKER = "GENERATED by scripts/sync-plugin-package.py"


def encoded(value):
    return json.dumps(value, indent=2, ensure_ascii=False) + "\n"


def outputs(root):
    package = json.loads((root / "plugin.json").read_text())
    skill = root / "skills/ui-qa/SKILL.md"
    if not skill.is_file() or not (root / "mcp.json").is_file():
        raise ValueError("plugin requires the canonical skill and mcp.json")
    identity = {key: package[key] for key in (
        "name", "version", "description", "author", "homepage", "repository", "license"
    )}
    if identity["name"] != "user-zero":
        raise ValueError("plugin name must remain user-zero; agent and catalog bindings use it")
    claude = dict(identity, mcpServers="./mcp.json")
    codex = dict(identity, skills="./skills/", mcpServers="./mcp.json")
    claude_catalog = {
        "name": "user-zero", "owner": package["author"],
        "metadata": {"description": package["description"]},
        "plugins": [{"name": "user-zero", "source": "./", "description": package["description"]}]
    }
    codex_catalog = {
        "name": "user-zero", "plugins": [{
            "name": "user-zero", "source": {"source": "local", "path": "./"},
            "policy": {"installation": "AVAILABLE", "authentication": "ON_INSTALL"},
            "category": "Productivity"
        }]
    }
    agent = f'''---
name: user-zero
description: {package["description"]}
tools: Read, Write, mcp__plugin_user-zero_playwright
---

<!-- {MARKER} — do not edit. -->

Your canonical persona is `${{CLAUDE_PLUGIN_ROOT}}/skills/ui-qa/agents/user-zero.md`.
Read it in full, then read the taxonomy and selected lenses from the same
skill root. Follow the mission packet using the bundled Playwright adapter.
All method paths resolve from `${{CLAUDE_PLUGIN_ROOT}}/skills/ui-qa/`, never
from the product repository or the process working directory. If the host
does not expand the plugin-root variable, use the packet's absolute `method_root`
instead; do not guess a repository-relative path.

Product routes and the evidence directory come only from the mission packet.
Pass A receives no source, specs, product instruction files, or oracle values.
Write only to the evidence directory and include the canonical read declaration.
'''
    result = {
        ".claude-plugin/plugin.json": encoded(claude),
        ".claude-plugin/marketplace.json": encoded(claude_catalog),
        ".codex-plugin/plugin.json": encoded(codex),
        ".agents/plugins/marketplace.json": encoded(codex_catalog),
        "agents/user-zero.md": agent,
    }
    for path in list(result):
        if path.endswith(".json"):
            file = Path(path)
            result[str(file.with_name("." + file.name + ".ui-qa-managed"))] = MARKER + "\n"
    return result


def safe_path(root, relative):
    current = root
    for part in Path(relative).parts:
        current = current / part
        if current.is_symlink():
            raise ValueError(f"refusing symlinked plugin output: {relative}")
    return current


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parent.parent)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = args.root.resolve()
    expected = outputs(root)
    # Preflight the entire write set, including ownership markers, before edits.
    for relative in expected:
        target = safe_path(root, relative)
        if target.exists() and not target.is_file():
            raise ValueError(f"plugin output is not a file: {relative}")
        if not args.check and target.exists():
            if relative.endswith(".json"):
                owner = safe_path(root, str(Path(relative).with_name("." + target.name + ".ui-qa-managed")))
                owned = owner.is_file() and owner.read_text() == MARKER + "\n"
            else:
                owned = MARKER in target.read_text()
            if not owned:
                raise ValueError(f"refusing to overwrite unowned plugin file: {relative}")
    drift = []
    for relative, content in expected.items():
        target = root / relative
        if args.check:
            if not target.is_file() or target.read_text() != content:
                drift.append(relative)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content)
    if drift:
        print("plugin package out of sync: " + ", ".join(drift), file=sys.stderr)
        return 1
    print("plugin: " + ("in sync" if args.check else "generated host bindings; canonical skill unchanged"))
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (OSError, ValueError, KeyError) as error:
        print(f"plugin: {error}", file=sys.stderr)
        sys.exit(1)
