#!/usr/bin/env bash
# Generate the per-platform pointer stubs from the canonical skill.
#
# Scheme: the skill exists exactly ONCE, at $BASE (default skills/ui-qa).
# Each platform gets a small generated stub carrying only what that platform
# needs for discovery, which then points at the canonical files. No content is
# duplicated, so platforms cannot drift from each other -- only the stubs can
# drift from the generator, and check-platform-sync.sh catches that.
#
# Usage:
#   scripts/sync-platform-dirs.sh
#   scripts/sync-platform-dirs.sh --root /path/to/repo --base skills/ui-qa \
#                                 --platforms "claude codex" --adapter playwright-mcp
#
# Platform layouts (see docs/OPERATIONS.md §Platform layouts for provenance):
#   claude  .claude/skills/ui-qa/SKILL.md, .claude/agents/user-zero.md,
#           .claude/commands/ui-qa.md
#   codex   .agents/skills/ui-qa/{SKILL.md,agents/openai.yaml}   <- documented location
#           .codex/skills/ui-qa/SKILL.md                          <- compatibility copy
#   cursor  .cursor/skills/ui-qa/SKILL.md
#   gemini  .gemini/skills/ui-qa/SKILL.md

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib-common.sh
. "$HERE/lib-common.sh"

ROOT="$(cd "$HERE/.." && pwd)"
BASE="skills/ui-qa"
PLATFORMS="claude codex"
ADAPTER="playwright-mcp"

while [ $# -gt 0 ]; do
  case "$1" in
    --root) ROOT="$2"; shift 2 ;;
    --base) BASE="$2"; shift 2 ;;
    --platforms) PLATFORMS="$2"; shift 2 ;;
    --adapter) ADAPTER="$2"; shift 2 ;;
    -h|--help) sed -n '2,26p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) echo "sync: unknown argument: $1" >&2; exit 2 ;;
  esac
done

validate_rel_path "$BASE" "--base" || exit 2
case "$ADAPTER" in *[!A-Za-z0-9._-]*) echo "sync: bad --adapter: $ADAPTER" >&2; exit 2 ;; esac
if is_platform_path "$BASE"; then
  echo "sync: refusing --base inside a platform directory ($BASE): the canonical" >&2
  echo "      skill and its own generated pointer would be the same file." >&2
  exit 2
fi

CANON="$ROOT/$BASE"
[ -f "$CANON/SKILL.md" ] || { echo "sync: no canonical skill at $CANON/SKILL.md" >&2; exit 1; }
[ -f "$CANON/adapters/$ADAPTER.md" ] || {
  echo "sync: no adapter file at $BASE/adapters/$ADAPTER.md" >&2; exit 1; }

# --- Adapter drives the agent's tool grant, so "adapters are interchangeable"
# --- stays true of the generated stubs too, not only of the prose.
case "$ADAPTER" in
  playwright-mcp) AGENT_TOOLS="Read, Write, mcp__playwright"; MCP_ID="playwright" ;;
  # The Chrome extension's tool names vary by version and cannot be pinned here.
  # An empty grant means the stub OMITS its tools line and inherits the
  # session's tools -- broader than we like; the adapter's first-use checklist
  # says to tighten it once the real names are recorded.
  claude-chrome)  AGENT_TOOLS=""; MCP_ID="" ;;
  *)              AGENT_TOOLS="Read, Write"; MCP_ID="" ;;
esac

# --- Frontmatter is extracted, never retyped, so the description cannot drift.
FM="$(awk 'NR==1 && $0=="---" {inside=1; next} inside && $0=="---" {exit} inside {print}' "$CANON/SKILL.md")"
[ -n "$FM" ] || { echo "sync: $CANON/SKILL.md has no frontmatter block" >&2; exit 1; }

AGENT_DESC="$(awk '/^description:/{sub(/^description: */,""); print; exit}' <<<"$FM")"
[ -n "$AGENT_DESC" ] || { echo "sync: canonical SKILL.md frontmatter has no description" >&2; exit 1; }

GEN_NOTE="<!-- $UI_QA_GEN_MARKER from $BASE — do not edit. -->"

# Every write is ownership-gated. A user may legitimately keep their own skill,
# agent, or command at the same conventional path; clobbering it would be the
# same defect as deleting an unowned --dest, on a different surface.
REFUSED=0
claim_path() {   # 0 = ours to write, 1 = leave it alone
  local rel="$1"
  if is_generated_or_absent "$ROOT/$rel"; then return 0; fi
  echo "sync: refusing to overwrite $rel — it exists and was not generated by" >&2
  echo "      this script. Move it aside, or generate for a different platform." >&2
  REFUSED=$((REFUSED+1))
  return 1
}

write_skill_stub() {
  local rel="$1" dest
  claim_path "$rel" || return 0
  safe_prepare_file "$ROOT" "$rel" || exit 1
  dest="$ROOT/$rel"
  {
    printf -- '---\n%s\n---\n\n' "$FM"
    printf -- '%s\n\n' "$GEN_NOTE"
    cat <<EOF
# ui-qa (pointer)

The canonical skill lives at \`$BASE/SKILL.md\`. **Read it in full now**, then
follow it. Every path inside it is relative to \`$BASE/\`.

Companion files you will be told to read from there:

| File | What it is |
|---|---|
| \`$BASE/agents/user-zero.md\` | the evaluator persona dispatched for Pass A |
| \`$BASE/references/pass-a-dispatch.md\` | how to dispatch Pass A without contaminating it |
| \`$BASE/references/ux-evaluation-taxonomy.md\` | the always-loaded expert question catalog |
| \`$BASE/lenses/MANIFEST.md\` | optional per-charter lens packs |
| \`$BASE/references/charter-schema.md\` | charter sections + the Pass-A contamination boundary |
| \`$BASE/references/coverage-contract.md\` | the coverage matrix and the gate a run must pass |
| \`$BASE/references/evidence-schema.md\` | finding records, exit interview, PROOF debrief |
| \`$BASE/references/calibration-protocol.md\` | how the harness itself is measured |
| \`$BASE/references/persona-cohorts.md\` | \`--cohort\` mode |
| \`$BASE/references/profile-schema.md\` | the product binding + onboarding |
| \`$BASE/references/expectation-synthesis.md\` | \`explore\` mode |
| \`$BASE/references/browser-driver-contract.md\` | abstract browser capabilities |
| \`$BASE/adapters/$ADAPTER.md\` | the bound browser-tool adapter |

This file is a pointer so that every harness dispatches the identical
evaluator from one source of truth.
EOF
  } > "$dest"
}

write_agent_stub() {
  local rel="$1" dest tools_line=""
  claim_path "$rel" || return 0
  safe_prepare_file "$ROOT" "$rel" || exit 1
  dest="$ROOT/$rel"
  # An empty grant omits the line entirely: the agent inherits session tools
  # (used by adapters whose tool names cannot be pinned, e.g. claude-chrome).
  [ -n "$AGENT_TOOLS" ] && tools_line="tools: $AGENT_TOOLS"
  cat > "$dest" <<EOF
---
name: user-zero
description: $AGENT_DESC
${tools_line}
---

$GEN_NOTE

You are the user-zero agent. Your full persona, evaluation remit, methods
(cognitive walkthrough + heuristic sweep), sensing rules, hard rules, and
output contract are defined in:

1. \`$BASE/agents/user-zero.md\` — who you are, how you work
2. \`$BASE/references/ux-evaluation-taxonomy.md\` — your expert question
   catalog; read before your first screen
3. \`$BASE/lenses/<name>.md\` — any lens packs your mission packet names
4. \`$BASE/references/evidence-schema.md\` — finding-record, exit-interview,
   and debrief formats
5. \`$BASE/adapters/$ADAPTER.md\` — your browser tooling and its caveats

Read 1, 2, 3 in that order, then execute the mission packet you were given.
The taxonomy and lenses are your own professional expertise and are always
allowed; the product's specs, state models, and source code are NOT yours to
read unless the packet explicitly hands them to you (an informed Pass-B packet
may; a fresh-eyes Pass-A packet never does).

Your report MUST end with the read-declaration required by
\`$BASE/references/pass-a-dispatch.md\`: every file you read and every command
you ran. A Pass-A run whose declaration lists anything outside your packet is
void, and concealing a read is a worse failure than admitting one.

DO NOT run \`git stash\`, \`git reset\`, \`git checkout\`, \`git clean\`,
\`git restore\`, or any destructive git command. Read-only git commands are
fine. You mutate the application only through its UI, only within the
packet's allowed mutations, and you write only into the packet's evidence
directory.
EOF
}

write_command_stub() {
  local rel="$1" dest
  claim_path "$rel" || return 0
  safe_prepare_file "$ROOT" "$rel" || exit 1
  dest="$ROOT/$rel"
  cat > "$dest" <<EOF
---
description: Run a human-style UI QA charter (ui-qa harness)
argument-hint: "[charter ...] | explore <target> | <charter> --cohort <persona,...>"
---

$GEN_NOTE

Read \`$BASE/SKILL.md\` in full, then execute it with these arguments:

\$ARGUMENTS

Argument forms are defined in the skill's Invocation section. With no
arguments, list the available charters and their isolation classes; do not
run anything.
EOF
}

# Codex's documented per-skill agent metadata file.
write_openai_yaml() {
  local rel="$1" dest
  claim_path "$rel" || return 0
  safe_prepare_file "$ROOT" "$rel" || exit 1
  dest="$ROOT/$rel"
  {
    cat <<EOF
# $UI_QA_GEN_MARKER from $BASE — do not edit.
interface:
  display_name: "ui-qa — human-style UI QA explorer"
  short_description: "Drive the real UI as a senior UX evaluator; produce evidence-backed findings."
  default_prompt: |
    Read $BASE/SKILL.md in full, then follow it. The evaluator persona is
    $BASE/agents/user-zero.md and its expertise is
    $BASE/references/ux-evaluation-taxonomy.md plus any lenses the charter names.
policy:
  allow_implicit_invocation: false
EOF
    if [ -n "$MCP_ID" ]; then
      cat <<EOF
dependencies:
  tools:
    - type: "mcp"
      value: "$MCP_ID"
EOF
    fi
  } > "$dest"
}

for p in $PLATFORMS; do
  case "$p" in claude|codex|cursor|gemini) ;; *) echo "sync: unknown platform: $p" >&2; exit 2 ;; esac
done

# Every path this generator owns, per platform. Pruning uses this list and only
# this list -- a generated tree is never cleaned by pattern or by guesswork.
platform_paths() {
  case "$1" in
    claude) printf '%s\n' .claude/skills/ui-qa/SKILL.md .claude/agents/user-zero.md .claude/commands/ui-qa.md ;;
    # Documented location: $REPO_ROOT/.agents/skills (learn.chatgpt.com/docs/build-skills).
    # .codex/skills is a compatibility copy: some builds and wrappers scan it.
    codex)  printf '%s\n' .agents/skills/ui-qa/SKILL.md .agents/skills/ui-qa/agents/openai.yaml .codex/skills/ui-qa/SKILL.md ;;
    cursor) printf '%s\n' .cursor/skills/ui-qa/SKILL.md ;;
    gemini) printf '%s\n' .gemini/skills/ui-qa/SKILL.md ;;
  esac
}

selected() { case " $PLATFORMS " in *" $1 "*) return 0 ;; *) return 1 ;; esac; }

for p in $PLATFORMS; do
  case "$p" in
    claude)
      write_skill_stub   .claude/skills/ui-qa/SKILL.md
      write_agent_stub   .claude/agents/user-zero.md
      write_command_stub .claude/commands/ui-qa.md
      ;;
    codex)
      write_skill_stub   .agents/skills/ui-qa/SKILL.md
      write_openai_yaml  .agents/skills/ui-qa/agents/openai.yaml
      write_skill_stub   .codex/skills/ui-qa/SKILL.md
      ;;
    cursor) write_skill_stub .cursor/skills/ui-qa/SKILL.md ;;
    gemini) write_skill_stub .gemini/skills/ui-qa/SKILL.md ;;
  esac
  echo "sync: wrote $p stubs -> $BASE (adapter: $ADAPTER)"
done

# Prune stubs for platforms no longer selected. Without this, narrowing
# --platforms leaves an obsolete stub behind that still points at the skill and
# still gets loaded -- a stale evaluator nobody meant to keep.
for p in claude codex cursor gemini; do
  selected "$p" && continue
  pruned=0
  while read -r rel; do
    [ -n "$rel" ] || continue
    # Never delete through a symlinked parent: the path we resolve would not be
    # the path we meant. Report and skip rather than guessing.
    if ! assert_no_symlink_path "$ROOT" "$(dirname "$rel")" 2>/dev/null; then
      echo "sync: skipping prune of $rel (symlinked parent)" >&2
      continue
    fi
    # Prune ONLY files this generator wrote. A user's own skill or command at a
    # conventional path is not ours to delete because a platform was deselected.
    if [ -L "$ROOT/$rel" ]; then
      rm -f "$ROOT/$rel"; pruned=1
    elif [ -f "$ROOT/$rel" ]; then
      if is_generated_or_absent "$ROOT/$rel"; then
        rm -f "$ROOT/$rel"; pruned=1
      else
        echo "sync: not pruning $rel — it exists and was not generated here" >&2
        REFUSED=$((REFUSED+1))
      fi
    fi
  done < <(platform_paths "$p")
  # Remove now-empty directories we owned, innermost first, never their parents.
  for d in .claude/skills/ui-qa .claude/skills .claude/agents .claude/commands .claude \
           .agents/skills/ui-qa/agents .agents/skills/ui-qa .agents/skills .agents \
           .codex/skills/ui-qa .codex/skills .codex \
           .cursor/skills/ui-qa .cursor/skills .cursor \
           .gemini/skills/ui-qa .gemini/skills .gemini; do
    [ -d "$ROOT/$d" ] && [ ! -L "$ROOT/$d" ] && rmdir "$ROOT/$d" 2>/dev/null || true
  done
  [ "$pruned" -eq 1 ] && echo "sync: pruned obsolete $p stubs"
done

if [ "$REFUSED" -gt 0 ]; then
  echo "sync: FAILED — $REFUSED path(s) left untouched because they are not ours." >&2
  echo "      Nothing was overwritten or deleted. Resolve those paths, then re-run." >&2
  exit 1
fi
exit 0
