#!/usr/bin/env bash
# Remove the ui-qa harness from a repository.
#
#   scripts/uninstall.sh /path/to/repo [--purge-explorer] [--dry-run]
#
# Removes only what the installer created, and proves it before deleting:
#   * generated platform stubs      -- only files carrying the generator's marker
#   * the skill directory           -- only if it carries the .ui-qa-managed marker
#   * .ui-qa-install.json
#
# Keeps your work by default:
#   * <explorer-dir>/  (PROFILE.md, charters, calibration inputs)  -- --purge-explorer to remove
#   * qa-output/       (run evidence)                              -- never touched
#
# --dry-run prints the plan and changes nothing.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib-common.sh
. "$HERE/lib-common.sh"

TARGET=""; PURGE=0; DRY=0

while [ $# -gt 0 ]; do
  case "$1" in
    --purge-explorer) PURGE=1; shift ;;
    --dry-run) DRY=1; shift ;;
    -h|--help) sed -n '2,19p' "${BASH_SOURCE[0]}"; exit 0 ;;
    -*) echo "uninstall: unknown option: $1" >&2; exit 2 ;;
    *) [ -z "$TARGET" ] || { echo "uninstall: unexpected argument: $1" >&2; exit 2; }
       TARGET="$1"; shift ;;
  esac
done

[ -n "$TARGET" ] || { echo "uninstall: target repository path required" >&2; exit 2; }
[ -d "$TARGET" ] || { echo "uninstall: not a directory: $TARGET" >&2; exit 1; }
TARGET="$(cd "$TARGET" && pwd)"

MANIFEST="$TARGET/.ui-qa-install.json"
manifest_get() {
  [ -f "$MANIFEST" ] || return 0
  sed -n "s/.*\"$1\"[[:space:]]*:[[:space:]]*\"\([^\"]*\)\".*/\1/p" "$MANIFEST" | head -1
}
DEST="$(manifest_get dest)";                 DEST="${DEST:-skills/ui-qa}"
EXPLORER_DIR="$(manifest_get explorer_dir)"; EXPLORER_DIR="${EXPLORER_DIR:-qa/product-explorer}"

validate_rel_path "$DEST" "dest (from manifest)" || exit 2
validate_rel_path "$EXPLORER_DIR" "explorer_dir (from manifest)" || exit 2
if is_forbidden_dest "$DEST"; then
  echo "uninstall: manifest names a reserved directory ('$DEST'); refusing" >&2; exit 2
fi

say() {  # say <what> ; prints "removing X" or "would remove X"
  if [ "$DRY" -eq 1 ]; then echo "would remove  $*"; else echo "removing      $*"; fi
}
do_rm() { [ "$DRY" -eq 1 ] || rm -rf "$1"; }

removed=0; kept=0

# 1. generated stubs, for every platform this generator knows ---------------
STUBS="
.claude/skills/ui-qa/SKILL.md
.claude/agents/user-zero.md
.claude/commands/ui-qa.md
.agents/skills/ui-qa/SKILL.md
.agents/skills/ui-qa/agents/openai.yaml
.codex/skills/ui-qa/SKILL.md
.cursor/skills/ui-qa/SKILL.md
.gemini/skills/ui-qa/SKILL.md
"
for rel in $STUBS; do
  path="$TARGET/$rel"
  [ -e "$path" ] || [ -L "$path" ] || continue
  if ! assert_no_symlink_path "$TARGET" "$(dirname "$rel")" 2>/dev/null; then
    echo "keeping      $rel (symlinked parent — resolve it yourself)"; kept=$((kept+1)); continue
  fi
  if [ -L "$path" ] || is_generated_or_absent "$path"; then
    say "$rel"; do_rm "$path"; removed=$((removed+1))
  else
    echo "keeping      $rel (not generated by this harness — it is yours)"; kept=$((kept+1))
  fi
done

# Tidy directories we owned, innermost first. rmdir only, so a directory with
# anything else in it survives untouched.
if [ "$DRY" -eq 0 ]; then
  for d in .claude/skills/ui-qa .claude/skills .claude/agents .claude/commands .claude \
           .agents/skills/ui-qa/agents .agents/skills/ui-qa .agents/skills .agents \
           .codex/skills/ui-qa .codex/skills .codex \
           .cursor/skills/ui-qa .cursor/skills .cursor \
           .gemini/skills/ui-qa .gemini/skills .gemini; do
    [ -d "$TARGET/$d" ] && [ ! -L "$TARGET/$d" ] && rmdir "$TARGET/$d" 2>/dev/null || true
  done
fi

# 2. the skill directory ---------------------------------------------------
if [ -d "$TARGET/$DEST" ]; then
  if [ -f "$TARGET/$DEST/$UI_QA_MARKER" ]; then
    say "$DEST/ (carries the $UI_QA_MARKER marker)"
    do_rm "$TARGET/$DEST"; removed=$((removed+1))
    [ "$DRY" -eq 0 ] && rmdir "$(dirname "$TARGET/$DEST")" 2>/dev/null || true
  else
    echo "keeping      $DEST/ (no $UI_QA_MARKER marker — this installer did not create it)"
    kept=$((kept+1))
  fi
fi

# 3. your work -------------------------------------------------------------
if [ -d "$TARGET/$EXPLORER_DIR" ]; then
  if [ "$PURGE" -eq 1 ]; then
    say "$EXPLORER_DIR/ (--purge-explorer: profile, charters, calibration inputs)"
    do_rm "$TARGET/$EXPLORER_DIR"; removed=$((removed+1))
  else
    echo "keeping      $EXPLORER_DIR/ (your profile, charters and calibration inputs)"
    echo "          pass --purge-explorer to remove it too"
    kept=$((kept+1))
  fi
fi

# 4. the manifest ----------------------------------------------------------
if [ -f "$MANIFEST" ]; then
  say ".ui-qa-install.json"
  [ "$DRY" -eq 0 ] && rm -f "$MANIFEST"
  removed=$((removed+1))
fi

echo
[ "$DRY" -eq 1 ] && echo "uninstall: DRY RUN — nothing changed. $removed item(s) would go, $kept kept." \
                || echo "uninstall: done. $removed item(s) removed, $kept kept."

cat <<EOF

Three things are deliberately left for you, because they are not ours to edit:

1. The MCP server registration (.mcp.json for Claude Code, or the Codex config
   under CODEX_HOME). Remove the "playwright" entry if nothing else uses it.
2. The 'UI QA: read ...' line in your AGENTS.md / CLAUDE.md.
3. 'qa-output/' in .gitignore, and the qa-output/ directory itself if you no
   longer want the run evidence.
EOF
